# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/story.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/story.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/story.proto\"<\n\x0cStoryRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\x12\r\n\x05theme\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\"N\n\rStoryResponse\x12\r\n\x05story\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x0e\n\x06trends\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"\x1f\n\rTrendsRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\"0\n\x0eTrendsResponse\x12\x0e\n\x06trends\x18\x01 \x03(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2l\n\x0cStoryService\x12.\n\rGenerateStory\x12\r.StoryRequest\x1a\x0e.StoryResponse\x12,\n\tGetTrends\x12\x0e.TrendsRequest\x1a\x0f.TrendsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.story_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STORYREQUEST']._serialized_start=21
  _globals['_STORYREQUEST']._serialized_end=81
  _globals['_STORYRESPONSE']._serialized_start=83
  _globals['_STORYRESPONSE']._serialized_end=161
  _globals['_TRENDSREQUEST']._serialized_start=163
  _globals['_TRENDSREQUEST']._serialized_end=194
  _globals['_TRENDSRESPONSE']._serialized_start=196
  _globals['_TRENDSRESPONSE']._serialized_end=244
  _globals['_STORYSERVICE']._serialized_start=246
  _globals['_STORYSERVICE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
